# Generated by Django 5.2.1 on 2025-06-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_person_task_doneat_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="category",
            new_name="categoryId",
        ),
        migrations.AddField(
            model_name="task",
            name="personId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.person",
            ),
        ),
    ]
