# Generated by Django 5.2.1 on 2025-06-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_rename_category_task_categoryid_task_personid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="categoryId",
            new_name="category",
        ),
    ]
