# Generated by Django 5.2.1 on 2025-06-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_categoryid_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='personId',
            new_name='person',
        ),
    ]
